#!/bin/bash

set -e

chmod 770 /home/cif/tokens.sh
chmod 770 /home/cif/test.sh

/home/cif/tokens.sh

chown -R cif:cif /var/lib/cif
chown -R cif:cif /var/log/cif
chown -R cif:cif /var/lib/fm
chown -R cif:cif /etc/cif
chown -R cif:cif /home/cif

chmod -R 660 /etc/cif/rules
chmod 770 /etc/cif/rules
chmod 770 /etc/cif/rules/default

/usr/local/bin/supervisord -n -c /usr/local/etc/supervisord.conf